#!/usr/bin/env python3
"""Publish the contents of docs/ to the GitHub wiki.

The wiki is a *mirror*, not a second copy anyone edits. Everything is generated from the
markdown in this repository, so the two cannot drift: the files in docs/ are versioned
alongside the code they describe and come down with a clone, while the wiki exists only
so the same pages can be browsed without one.

Run it after changing any document:

    python tools/publish-wiki.py

The wiki repository has to exist before anything can be pushed to it, and GitHub only
creates it when the first page is saved through the web interface. There is no API for
that step. If this script reports that the remote is missing, open

    https://github.com/Nooziergg/library-loans-api/wiki

click "Create the first page", save anything at all, and run it again. Whatever you save
is overwritten on the first run.
"""
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile

WIKI_REMOTE = "https://github.com/Nooziergg/library-loans-api.wiki.git"
REPO_URL = "https://github.com/Nooziergg/library-loans-api"

# Source document -> wiki page name. The wiki namespace is flat, so the paths go away.
PAGES = [
    ("README.md", "Home"),
    ("docs/WALKTHROUGH.md", "Walkthrough"),
    ("docs/ARCHITECTURE.md", "Architecture"),
    ("docs/DECISIONS.md", "Decisions"),
    ("docs/AUTHORIZATION.md", "Authorization"),
    ("docs/PREREQUISITES.md", "Prerequisites"),
]

# Rewrite the repository's relative links into wiki page links.
LINK_MAP = {
    "docs/WALKTHROUGH.md": "Walkthrough",
    "docs/ARCHITECTURE.md": "Architecture",
    "docs/DECISIONS.md": "Decisions",
    "docs/AUTHORIZATION.md": "Authorization",
    "docs/PREREQUISITES.md": "Prerequisites",
    "WALKTHROUGH.md": "Walkthrough",
    "ARCHITECTURE.md": "Architecture",
    "DECISIONS.md": "Decisions",
    "AUTHORIZATION.md": "Authorization",
    "PREREQUISITES.md": "Prerequisites",
    "../README.md": "Home",
    "README.md": "Home",
}

SIDEBAR = """### Library Loans API

- [Home](Home)
- [Walkthrough](Walkthrough)
- [Architecture](Architecture)
- [Decisions](Decisions)
- [Authorization](Authorization)
- [Prerequisites](Prerequisites)

---

[Source repository](%s)
""" % REPO_URL


def banner(source):
    return (
        "> Mirrored from [`%s`](%s/blob/main/%s) in the repository, which is the source of\n"
        "> truth. This page is generated by `tools/publish-wiki.py`; edits made here are\n"
        "> overwritten on the next run.\n\n" % (source, REPO_URL, source)
    )


def rewrite_links(text):
    def replace(match):
        label, target = match.group(1), match.group(2)
        anchor = ""
        if "#" in target:
            target, anchor = target.split("#", 1)
            anchor = "#" + anchor
        if target in LINK_MAP:
            return "[%s](%s%s)" % (label, LINK_MAP[target], anchor)
        if target in ("LICENSE",):
            return "[%s](%s/blob/main/LICENSE)" % (label, REPO_URL)
        return match.group(0)

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", replace, text)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    checkout = tempfile.mkdtemp(prefix="wiki-")
    try:
        clone = subprocess.run(
            ["git", "clone", "--depth", "1", WIKI_REMOTE, checkout],
            capture_output=True, text=True,
        )
        if clone.returncode != 0:
            sys.stderr.write(clone.stderr)
            sys.stderr.write(
                "\nThe wiki repository does not exist yet. Open %s/wiki, click\n"
                "\"Create the first page\", save it, and run this again.\n" % REPO_URL
            )
            return 1

        for existing in os.listdir(checkout):
            if existing != ".git":
                path = os.path.join(checkout, existing)
                shutil.rmtree(path) if os.path.isdir(path) else os.remove(path)

        for source, page in PAGES:
            text = io.open(source, encoding="utf-8").read()
            body = banner(source) + rewrite_links(text)
            io.open(os.path.join(checkout, page + ".md"), "w",
                    encoding="utf-8", newline="\n").write(body)
            print("  %-22s -> %s" % (source, page))

        io.open(os.path.join(checkout, "_Sidebar.md"), "w",
                encoding="utf-8", newline="\n").write(SIDEBAR)

        subprocess.run(["git", "add", "-A"], cwd=checkout, check=True)
        status = subprocess.run(
            ["git", "status", "--porcelain"], cwd=checkout,
            capture_output=True, text=True, check=True,
        )
        if not status.stdout.strip():
            print("wiki already up to date")
            return 0

        subprocess.run(
            ["git", "commit", "-m", "Publish documentation from docs/"],
            cwd=checkout, check=True, capture_output=True,
        )
        push = subprocess.run(["git", "push"], cwd=checkout, capture_output=True, text=True)
        if push.returncode != 0:
            sys.stderr.write(push.stderr)
            return 1

        print("published %d pages" % (len(PAGES) + 1))
        return 0
    finally:
        shutil.rmtree(checkout, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
